version: '3.8'

services:
  web:
    build: . # このディレクトリにあるDockerfileをビルドする
    volumes:
      - .:/myapp #ホストの現在のディレクトリをコンテナの/myappディレクトリにマウント
    ports:
      - "3000:3000" #左側のホスト側のポートは自由に変更可
    depends_on:
      - db #dbを起動してからwebを起動する
    environment:
      DATABASE_URL: mysql2://myuser:mypass@db/mydb # 例のデータベースURL

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql # データベースデータを永続化する
    ports:
      -  "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass

volumes:
  db-data: {}