services:
  web:
    build: . # このディレクトリにあるDockerfileをビルドする
    volumes:
      - .:/myapp #ホストの現在のディレクトリをコンテナの/myappディレクトリにマウント
    ports:
      - '8000:8000' # ホストのポート:コンテナのポート
    depends_on:
      - db #dbを起動してからwebを起動する
    environment:
      DATABASE_URL: mysql2://myuser:mypass@db/task_app # 例のデータベースURL
    tty: true # ログに標準出力を表示
    stdin_open: true # ログに標準出力を表示
    networks:
      - app-net

  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # mysqlの文字コード
    volumes:
      - db-data:/var/lib/mysql # データベースデータを永続化する
      - ./task.sql:/docker-entrypoint-initdb.d/task.sql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: task_app
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    networks:
      - app-net

volumes:
  db-data: {}
networks:
  app-net:
    driver: bridge