services:
  web:
    build: . # このディレクトリにあるDockerfileをビルドする
    volumes:
      - .:/myapp #ホストの現在のディレクトリをコンテナの/myappディレクトリにマウント
    ports:
      - "8000:8000" #左側のホスト側のポートは自由に変更可
    depends_on:
      - db #dbを起動してからwebを起動する
    environment:
      DATABASE_URL: mysql2://myuser:mypass@db/mydb # 例のデータベースURL
    networks:
      - app-net

  db:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - db-data:/var/lib/mysql # データベースデータを永続化する
      - ./task.sql:/tmp/task.sql
    ports:
      -  "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    networks:
      - app-net

volumes:
  db-data: {}
networks:
  app-net:
    driver: bridge
