# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'bundler', '~> 2.5', '>= 2.5.6'
gem 'webrick', '~> 1.8', '>= 1.8.1'
gem 'mysql2', '~> 0.5.6'
gem 'erb', '~> 4.0', '>= 4.0.4'
gem 'cgi', '~> 0.4.1'
gem 'byebug'
